---
destination: _site
exclude:
    - build.sh
    - serve.sh
    - Gemfile
    - Gemfile.lock
timezone: America/Vancouver
encoding: UTF8-MAC

markdown: kramdown
kramdown:
    smart_quotes: 39,39,quot,quot
    entity_output: as_char


    # smart_quotes: lsquo,rsquo,ldquo,rdquo
